### ISSUE TITLE
Document `com.enonic.xp.extractor.cfg`

### ISSUE THREAD

**Issue by alansemenov** [enonic/doc-xp#167] opened 2020-08-19 08:23 UTC
We haven't documented `body.size.limit` property and the new config file `com.enonic.xp.extractor.cfg` implemented in
https://github.com/enonic/xp/issues/7294. 

Should be [here](https://developer.enonic.com/docs/xp/stable/deployment/config#xp_config_files)

**Comment by rymsha** [comment] 2021-11-16 16:49
Maybe it is a duplicate of #112 ? Or at least should be done together

**Closed** 2022-10-04 11:43 UTC
